import fs from 'node:fs/promises';
const file='research/check-interactions.mjs';
let text=await fs.readFile(file,'utf8');
text=text.replace('returnByValue:true,awaitPromise:true','returnByValue:true');
text=text.replace("await evaluate('Promise.race([document.fonts.ready,new Promise(r=>setTimeout(r,3000))])');", "for(let n=0;n<12;n++){if(await evaluate(\"document.fonts.status==='loaded'\"))break;await new Promise(r=>setTimeout(r,150));}");
text=text.replace("await send('Page.enable');", "await send('Page.bringToFront');await send('Page.enable');");
text=text.replace("document.querySelector('[data-filter]').value='Day 2';document.querySelector('[data-filter]').dispatchEvent(new Event('input'))", "document.querySelector('[data-collection-search]').value='Day 2';document.querySelector('[data-collection-search]').dispatchEvent(new Event('input'))");
const extra=`
await navigate('/gallery/2025',390);
check('Gallery initially shows 24 photos',await evaluate("document.querySelectorAll('.gallery-item:not([hidden])').length===24"));
await evaluate("document.querySelector('[data-category-filter=daytwo]').click()");
check('Day filter isolates day two',await evaluate("[...document.querySelectorAll('.gallery-item:not([hidden])')].every(i=>i.dataset.category==='daytwo')"));
await evaluate("document.querySelector('.gallery-item:not([hidden])').click();document.querySelector('.photo-next').click()");
check('Next photo updates counter',await evaluate("document.querySelector('[data-photo-count]').textContent.startsWith('2 /')"));
await send('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowLeft',code:'ArrowLeft',windowsVirtualKeyCode:37});
check('Left arrow navigates photos',await evaluate("document.querySelector('[data-photo-count]').textContent.startsWith('1 /')"));
await evaluate("document.querySelector('.dialog-close').click()");
await navigate('/speakers/rahgir',390);
check('English biography is default',await evaluate("!document.querySelector('#bio-en').hidden && document.querySelector('#bio-hi').hidden"));
await evaluate("document.querySelector('#bio-hi-tab').click()");
check('Hindi biography switch works',await evaluate("document.querySelector('#bio-en').hidden && !document.querySelector('#bio-hi').hidden && document.querySelector('#bio-hi').textContent.length>100"));
await screenshot('indore-hindi-profile');
await navigate('/journal');
await evaluate("document.querySelector('[data-category-filter=Conversations]').click()");
check('Journal categories work',await evaluate("document.querySelectorAll('.article-card:not([hidden])').length>0 && [...document.querySelectorAll('.article-card:not([hidden])')].every(i=>i.dataset.category==='Conversations')"));
await evaluate("document.querySelector('[data-category-filter=all]').click();document.querySelector('[data-load-more]').click()");
check('More stories reveals all 16 articles',await evaluate("document.querySelectorAll('.article-card:not([hidden])').length===16"));
await navigate('/faq',390);
await evaluate("document.querySelector('summary').click()");
check('FAQ opens with useful answer',await evaluate("document.querySelector('details').open"));
await navigate('/contact',390);
check('Enquiry requires message and name',await evaluate("!document.querySelector('[data-enquiry]').checkValidity()"));
`;
text=text.replace("check('No JavaScript exceptions'",extra+"\ncheck('No JavaScript exceptions'");
await fs.writeFile(file,text);
