@extends('frontend.layouts.app')
@section('content')
@include('frontend.partials.page-heading',['kicker'=>'STEP INSIDE INDORE LITERATURE FESTIVAL','intro'=>'Come for a favourite writer. Stay for an unexpected idea, a moving verse, a conversation that carries on long after the stage falls quiet.'])
<section class="experience-opening container section"><div><p class="eyebrow">A LITTLE OF EVERYTHING YOU LOVE</p><h2>Follow the words.<br><em>Find your world.</em></h2><p>Our festival brings literature, conversation, poetry, art and music into one shared space. Explore its different sides through our journal, photographs and the voices of previous editions.</p><nav class="experience-jumps" aria-label="Festival experiences"><a href="#conversations">Conversations ↓</a><a href="#poetry">Poetry & stories ↓</a><a href="#arts">Art & music ↓</a><a href="#your-stage">Your stage ↓</a></nav></div><img src="{{ $image('legacy/images/dayone/dayone2.jpeg') }}" alt="An audience sharing a festival moment" width="900" height="800" loading="lazy"></section>
@foreach([['conversations','01','A different point of view.','Listen. Question. See things anew.','Meet authors and thinkers in our 2025 speaker directory, then explore the ideas they brought to the festival through our journal.','legacy/images/slideshow-main/6.jpg','speakers','Meet the storytellers'],['poetry','02','Words that feel like home.','Poetry. Stories. A little silence in between.','Discover the festival’s love of language through Hindi writing, poetry and reflections preserved in the journal.','images/poetry-art.png','journal','Read the festival journal'],['arts','03','Beyond the written word.','Expression in every direction.','Revisit the people, performances and shared moments in our festival photographs. Our official YouTube channel keeps more of the conversations alive.','legacy/images/daythree/daythree13.jpeg','gallery','Open the memory book'],['your-stage','04','Maybe the next voice is yours.','Bring your words. Bring yourself.','Explore the 2026 open mic, volunteering and other ways to take part. Find the official application forms on our participation page.','images/conversation-art.png','participate','Explore participation']] as [$id,$number,$heading,$sub,$copy,$picture,$destination,$label])
<section id="{{ $id }}" class="experience-story container section" data-reveal><div class="experience-story-image"><img src="{{ $image($picture) }}" alt="{{ in_array($id,['poetry','your-stage'])?'Conceptual festival illustration':'A moment from the festival archive' }}" width="900" height="800" loading="lazy"><span>{{ $number }}</span></div><div><p class="eyebrow">{{ $sub }}</p><h2>{{ $heading }}</h2><p>{{ $copy }}</p><a class="button button-blue" href="{{ route($destination) }}">{{ $label }} ↗</a></div></section>
@endforeach
@include('frontend.partials.faq')
@endsection
