@extends('frontend.layouts.app')
@section('content')
@include('frontend.partials.page-heading',['kicker'=>'A LITTLE PLANNING. A LOT OF POSSIBILITY.','intro'=>'Your starting point for a day of words, ideas and discovery in Indore.'])
<section class="container section visit-overview"><div><p class="eyebrow">THE NEXT CHAPTER</p><h2>Leave room for<br><em>the unexpected.</em></h2><p>The best festival days begin with curiosity. Check the announcement here, explore the programme when it is available, and make time for a conversation you didn’t plan.</p></div><div class="visit-facts"><div><span>WHEN</span><strong>{{ $festival['dates'] ?: 'Dates to be announced' }}</strong></div><div><span>WHERE</span><strong>{{ $festival['venue'] ?: 'Indore · venue to be announced' }}</strong></div><div><span>REGISTRATION</span><a href="{{ route('participate') }}">Check participation updates ↗</a></div><p>The available programme is the 2025 archive. It is not the schedule for the next edition.</p></div></section>
<section class="visit-photo"><img src="{{ $image('legacy/images/dayone/dayone2.jpeg') }}" alt="Audience at the 2025 Indore Literature Festival" width="1400" height="700" loading="lazy"><div><p class="eyebrow">A CITY OF STORIES</p><h2>Come curious.<br><em>Leave inspired.</em></h2><span>Photograph from the 2025 edition</span></div></section>
<section class="container section"><div class="section-heading"><h2>Before you <em>set out.</em></h2></div><div class="planning-grid">@foreach([['01','Pick your conversations','Browse past speakers and stories for a sense of the festival. Use the next edition’s programme once it is announced.','schedule','Explore the programme archive'],['02','Check the details','Confirm the event venue and registration before making travel plans. The organising office is not the festival venue.','participate','View participation information'],['03','Let us help','For accessibility needs, a group visit or a specific question, contact the organising team before your visit.','contact','Contact the team']] as [$number,$heading,$copy,$destination,$label])<article data-reveal><span>{{ $number }}</span><h3>{{ $heading }}</h3><p>{{ $copy }}</p><a class="text-link" href="{{ route($destination) }}">{{ $label }} ↗</a></article>@endforeach</div></section>
<section class="container regional-note"><p class="eyebrow">STAY A LITTLE LONGER</p><h2>Indore first.<br><em>Then, a little Malwa.</em></h2><p>Explore our city and the neighbouring cultural destinations through the official visitor guides collected on our discovery page.</p><a class="button button-blue" href="{{ route('malwa') }}">Discover Malwa ↗</a></section>
@include('frontend.partials.faq')
@endsection
